### ISSUE TITLE
Windows builds are broken with v1.4.7

### ISSUE THREAD

**Issue by yurishkuro** [hashicorp/go-plugin#225]
dependabot tried to upgrade [1] Jaeger to v1.4.7 and failed with this error when building binaries with `GOOS=windows GOARCH=amd64`:
```
# github.com/hashicorp/go-plugin
Error: ../../../go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.7/client.go:512:36: undefined: syscall.Stat_t
```

Looks like a new dependency was introduced in #223.

[1]: https://github.com/jaegertracing/jaeger/pull/4089
